### ISSUE TITLE
Status actual

### ISSUE THREAD

**Issue by dmarman** [Kikobeats/forocoches-api#3]
Sigue en pie esta API? Donde obtengo una key?

**Comment by Kikobeats** [comment]
Hola! Fue un experimento, ahora mismo lo tengo un poco parado.

Tuve que hacer un proxy para establecer bien la codificación https://github.com/Kikobeats/forocoches-proxy

y en definitiva es un proceso un poco tedioso. Lo retomaré pero aún le queda un poco 😄
